[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Posvian <posvianski@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
